"""add social models

Revision ID: 0b644135cc28
Revises: fa58323a57e7
Create Date: 2020-02-04 22:19:18.351480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b644135cc28'
down_revision = 'fa58323a57e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_genders_id'), 'bio_genders', ['id'], unique=True)
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friends_date_created'), 'friends', ['date_created'], unique=False)
    op.create_index(op.f('ix_friends_friend_id'), 'friends', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friends_id'), 'friends', ['id'], unique=True)
    op.create_index(op.f('ix_friends_user_id'), 'friends', ['user_id'], unique=False)
    op.create_table('psy_genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color')
    )
    op.create_index(op.f('ix_psy_genders_id'), 'psy_genders', ['id'], unique=True)
    op.create_table('users_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_emails_date_created'), 'users_emails', ['date_created'], unique=False)
    op.create_index(op.f('ix_users_emails_id'), 'users_emails', ['id'], unique=True)
    op.create_index(op.f('ix_users_emails_user_id'), 'users_emails', ['user_id'], unique=False)
    op.create_table('users_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phones_date_created'), 'users_phones', ['date_created'], unique=False)
    op.create_index(op.f('ix_users_phones_id'), 'users_phones', ['id'], unique=True)
    op.create_index(op.f('ix_users_phones_user_id'), 'users_phones', ['user_id'], unique=False)
    op.create_table('users_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_photos_date_created'), 'users_photos', ['date_created'], unique=False)
    op.create_index(op.f('ix_users_photos_id'), 'users_photos', ['id'], unique=True)
    op.create_index(op.f('ix_users_photos_user_id'), 'users_photos', ['user_id'], unique=False)
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bio_gender_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('email_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('psy_gender_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_avatar_id'), 'users', ['avatar_id'], unique=False)
    op.create_index(op.f('ix_users_bio_gender_id'), 'users', ['bio_gender_id'], unique=False)
    op.create_index(op.f('ix_users_email_id'), 'users', ['email_id'], unique=False)
    op.create_index(op.f('ix_users_phone_id'), 'users', ['phone_id'], unique=False)
    op.create_index(op.f('ix_users_psy_gender_id'), 'users', ['psy_gender_id'], unique=False)
    op.create_foreign_key(None, 'users', 'psy_genders', ['psy_gender_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users_phones', ['phone_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users_photos', ['avatar_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users_emails', ['email_id'], ['id'])
    op.create_foreign_key(None, 'users', 'bio_genders', ['bio_gender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_psy_gender_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_id'), table_name='users')
    op.drop_index(op.f('ix_users_bio_gender_id'), table_name='users')
    op.drop_index(op.f('ix_users_avatar_id'), table_name='users')
    op.drop_column('users', 'psy_gender_id')
    op.drop_column('users', 'phone_id')
    op.drop_column('users', 'email_id')
    op.drop_column('users', 'bio_gender_id')
    op.drop_column('users', 'avatar_id')
    op.drop_index(op.f('ix_users_photos_user_id'), table_name='users_photos')
    op.drop_index(op.f('ix_users_photos_id'), table_name='users_photos')
    op.drop_index(op.f('ix_users_photos_date_created'), table_name='users_photos')
    op.drop_table('users_photos')
    op.drop_index(op.f('ix_users_phones_user_id'), table_name='users_phones')
    op.drop_index(op.f('ix_users_phones_id'), table_name='users_phones')
    op.drop_index(op.f('ix_users_phones_date_created'), table_name='users_phones')
    op.drop_table('users_phones')
    op.drop_index(op.f('ix_users_emails_user_id'), table_name='users_emails')
    op.drop_index(op.f('ix_users_emails_id'), table_name='users_emails')
    op.drop_index(op.f('ix_users_emails_date_created'), table_name='users_emails')
    op.drop_table('users_emails')
    op.drop_index(op.f('ix_psy_genders_id'), table_name='psy_genders')
    op.drop_table('psy_genders')
    op.drop_index(op.f('ix_friends_user_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_friend_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_date_created'), table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_bio_genders_id'), table_name='bio_genders')
    op.drop_table('bio_genders')
    # ### end Alembic commands ###
