"""add social models 4

Revision ID: 21359e785fa2
Revises: dccac3d7c5f1
Create Date: 2020-02-04 22:30:59.115021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21359e785fa2'
down_revision = 'dccac3d7c5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['users_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_friends_friend_id'), 'tags_friends', ['friend_id'], unique=False)
    op.create_index(op.f('ix_tags_friends_id'), 'tags_friends', ['id'], unique=True)
    op.create_index(op.f('ix_tags_friends_tag_id'), 'tags_friends', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_friends_tag_id'), table_name='tags_friends')
    op.drop_index(op.f('ix_tags_friends_id'), table_name='tags_friends')
    op.drop_index(op.f('ix_tags_friends_friend_id'), table_name='tags_friends')
    op.drop_table('tags_friends')
    # ### end Alembic commands ###
