"""add sports models 2

Revision ID: 3cfdc4607681
Revises: c14ef64f22d1
Create Date: 2020-02-04 23:50:27.818024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfdc4607681'
down_revision = 'c14ef64f22d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helpers_id'), 'helpers', ['id'], unique=True)
    op.create_index(op.f('ix_helpers_training_id'), 'helpers', ['training_id'], unique=False)
    op.create_index(op.f('ix_helpers_user_id'), 'helpers', ['user_id'], unique=False)
    op.add_column('exercises_tags', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_exercises_tags_tag_id'), 'exercises_tags', ['tag_id'], unique=False)
    op.create_foreign_key(None, 'exercises_tags', 'sport_tags', ['tag_id'], ['id'])
    op.add_column('trainings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_trainings_user_id'), 'trainings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'trainings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_index(op.f('ix_trainings_user_id'), table_name='trainings')
    op.drop_column('trainings', 'user_id')
    op.drop_constraint(None, 'exercises_tags', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_tags_tag_id'), table_name='exercises_tags')
    op.drop_column('exercises_tags', 'tag_id')
    op.drop_index(op.f('ix_helpers_user_id'), table_name='helpers')
    op.drop_index(op.f('ix_helpers_training_id'), table_name='helpers')
    op.drop_index(op.f('ix_helpers_id'), table_name='helpers')
    op.drop_table('helpers')
    # ### end Alembic commands ###
