"""add social models 2

Revision ID: 7abb79bb96fd
Revises: 0b644135cc28
Create Date: 2020-02-04 22:24:05.722481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abb79bb96fd'
down_revision = '0b644135cc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
