"""add adm 1

Revision ID: 7bde94a75d45
Revises: ee4551934edd
Create Date: 2020-02-04 23:57:44.425418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bde94a75d45'
down_revision = 'ee4551934edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
