"""add sports models 1

Revision ID: c14ef64f22d1
Revises: 21359e785fa2
Create Date: 2020-02-04 23:47:54.837232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14ef64f22d1'
down_revision = '21359e785fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_date_created'), 'exercises', ['date_created'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=True)
    op.create_table('exercises_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_photos_date_created'), 'exercises_photos', ['date_created'], unique=False)
    op.create_index(op.f('ix_exercises_photos_exercise_id'), 'exercises_photos', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercises_photos_id'), 'exercises_photos', ['id'], unique=True)
    op.create_table('exercises_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_tags_exercise_id'), 'exercises_tags', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercises_tags_id'), 'exercises_tags', ['id'], unique=True)
    op.create_table('exercises_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_videos_date_created'), 'exercises_videos', ['date_created'], unique=False)
    op.create_index(op.f('ix_exercises_videos_exercise_id'), 'exercises_videos', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercises_videos_id'), 'exercises_videos', ['id'], unique=True)
    op.create_table('sport_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color')
    )
    op.create_index(op.f('ix_sport_tags_date_created'), 'sport_tags', ['date_created'], unique=False)
    op.create_index(op.f('ix_sport_tags_id'), 'sport_tags', ['id'], unique=True)
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainings_date_created'), 'trainings', ['date_created'], unique=False)
    op.create_index(op.f('ix_trainings_id'), 'trainings', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainings_id'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_date_created'), table_name='trainings')
    op.drop_table('trainings')
    op.drop_index(op.f('ix_sport_tags_id'), table_name='sport_tags')
    op.drop_index(op.f('ix_sport_tags_date_created'), table_name='sport_tags')
    op.drop_table('sport_tags')
    op.drop_index(op.f('ix_exercises_videos_id'), table_name='exercises_videos')
    op.drop_index(op.f('ix_exercises_videos_exercise_id'), table_name='exercises_videos')
    op.drop_index(op.f('ix_exercises_videos_date_created'), table_name='exercises_videos')
    op.drop_table('exercises_videos')
    op.drop_index(op.f('ix_exercises_tags_id'), table_name='exercises_tags')
    op.drop_index(op.f('ix_exercises_tags_exercise_id'), table_name='exercises_tags')
    op.drop_table('exercises_tags')
    op.drop_index(op.f('ix_exercises_photos_id'), table_name='exercises_photos')
    op.drop_index(op.f('ix_exercises_photos_exercise_id'), table_name='exercises_photos')
    op.drop_index(op.f('ix_exercises_photos_date_created'), table_name='exercises_photos')
    op.drop_table('exercises_photos')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_date_created'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
