"""add social models 3

Revision ID: dccac3d7c5f1
Revises: 7abb79bb96fd
Create Date: 2020-02-04 22:29:54.526120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccac3d7c5f1'
down_revision = '7abb79bb96fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_social_date_created'), 'users_social', ['date_created'], unique=False)
    op.create_index(op.f('ix_users_social_id'), 'users_social', ['id'], unique=True)
    op.create_index(op.f('ix_users_social_user_id'), 'users_social', ['user_id'], unique=False)
    op.create_table('users_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color')
    )
    op.create_index(op.f('ix_users_tags_date_created'), 'users_tags', ['date_created'], unique=False)
    op.create_index(op.f('ix_users_tags_id'), 'users_tags', ['id'], unique=True)
    op.create_index(op.f('ix_users_tags_user_id'), 'users_tags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tags_user_id'), table_name='users_tags')
    op.drop_index(op.f('ix_users_tags_id'), table_name='users_tags')
    op.drop_index(op.f('ix_users_tags_date_created'), table_name='users_tags')
    op.drop_table('users_tags')
    op.drop_index(op.f('ix_users_social_user_id'), table_name='users_social')
    op.drop_index(op.f('ix_users_social_id'), table_name='users_social')
    op.drop_index(op.f('ix_users_social_date_created'), table_name='users_social')
    op.drop_table('users_social')
    # ### end Alembic commands ###
