"""add sports models 3

Revision ID: dde9b1c1a282
Revises: 3cfdc4607681
Create Date: 2020-02-04 23:55:47.086523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde9b1c1a282'
down_revision = '3cfdc4607681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('timer', sa.TIME(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('other', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_params_list_date_created'), 'params_list', ['date_created'], unique=False)
    op.create_index(op.f('ix_params_list_id'), 'params_list', ['id'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('will', sa.Boolean(), nullable=True),
    sa.Column('do', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_date_created'), 'participants', ['date_created'], unique=False)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=True)
    op.create_index(op.f('ix_participants_training_id'), 'participants', ['training_id'], unique=False)
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('timer', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_date_created'), 'rounds', ['date_created'], unique=False)
    op.create_index(op.f('ix_rounds_id'), 'rounds', ['id'], unique=True)
    op.create_index(op.f('ix_rounds_number'), 'rounds', ['number'], unique=False)
    op.create_index(op.f('ix_rounds_training_id'), 'rounds', ['training_id'], unique=False)
    op.create_table('users_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timer', sa.TIME(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('other', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_results_date_created'), 'users_results', ['date_created'], unique=False)
    op.create_index(op.f('ix_users_results_id'), 'users_results', ['id'], unique=True)
    op.create_index(op.f('ix_users_results_user_id'), 'users_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_results_user_id'), table_name='users_results')
    op.drop_index(op.f('ix_users_results_id'), table_name='users_results')
    op.drop_index(op.f('ix_users_results_date_created'), table_name='users_results')
    op.drop_table('users_results')
    op.drop_index(op.f('ix_rounds_training_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_number'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_date_created'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_training_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_date_created'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_params_list_id'), table_name='params_list')
    op.drop_index(op.f('ix_params_list_date_created'), table_name='params_list')
    op.drop_table('params_list')
    # ### end Alembic commands ###
