"""add sports models 4

Revision ID: ee4551934edd
Revises: dde9b1c1a282
Create Date: 2020-02-04 23:56:38.981518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4551934edd'
down_revision = 'dde9b1c1a282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_list_date_created'), 'exercises_list', ['date_created'], unique=False)
    op.create_index(op.f('ix_exercises_list_exercise_id'), 'exercises_list', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercises_list_id'), 'exercises_list', ['id'], unique=True)
    op.create_index(op.f('ix_exercises_list_round_id'), 'exercises_list', ['round_id'], unique=False)
    op.add_column('params_list', sa.Column('exercises_list_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_params_list_exercises_list_id'), 'params_list', ['exercises_list_id'], unique=False)
    op.create_foreign_key(None, 'params_list', 'exercises_list', ['exercises_list_id'], ['id'])
    op.add_column('users_results', sa.Column('exercises_list_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_results_exercises_list_id'), 'users_results', ['exercises_list_id'], unique=False)
    op.create_foreign_key(None, 'users_results', 'exercises_list', ['exercises_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_results', type_='foreignkey')
    op.drop_index(op.f('ix_users_results_exercises_list_id'), table_name='users_results')
    op.drop_column('users_results', 'exercises_list_id')
    op.drop_constraint(None, 'params_list', type_='foreignkey')
    op.drop_index(op.f('ix_params_list_exercises_list_id'), table_name='params_list')
    op.drop_column('params_list', 'exercises_list_id')
    op.drop_index(op.f('ix_exercises_list_round_id'), table_name='exercises_list')
    op.drop_index(op.f('ix_exercises_list_id'), table_name='exercises_list')
    op.drop_index(op.f('ix_exercises_list_exercise_id'), table_name='exercises_list')
    op.drop_index(op.f('ix_exercises_list_date_created'), table_name='exercises_list')
    op.drop_table('exercises_list')
    # ### end Alembic commands ###
